[package]
name = "freq"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
crossbeam-channel = "0.5.13"
itertools = "0.13.0"
memchr = "2.7.4"

[dev-dependencies]
tempfile = "3.13.0"

[profile.release]
debug = true
opt-level = 3